use_conda: true

experiments:
  bcalm2:
    "GCF_000008865.2_ASM886v2":
      k: [31, 51]
      bcalm2_abundance_min: [1]
      circularised: [true]
      filter_retain: "NC_002695.2"
      algorithm: ["unitigs", "omnitigs", "trivialomnitigs"]

    "GCF_000008025.1_ASM802v1":
      k: [51]
      bcalm2_abundance_min: [1]
      circularised: [true]
      filter_retain: "NC_002978.6"
      algorithm: ["unitigs", "omnitigs", "trivialomnitigs"]

    #"GRCh38_latest":
    #  k: [51]
    #  bcalm2_abundance_min: [1]
    #  circularised: [true]
    #  filter_retain: "NC_000010.11"
    #  algorithm: ["unitigs", "omnitigs", "trivialomnitigs"]
    #  url: "ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz"

  wtdbg2:
    "C.elegans":
      urls: ["http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/40X/polished_assembly/pREADS_data-corrected.fasta"]
      reference: "http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/40X/polished_assembly/polished_assembly.fasta.gz"
      algorithm: ["unitigs", "omnitigs", "trivialomnitigs"]

    "A.thaliana":
      urls: ["https://downloads.pacbcloud.com/public/SequelData/ArabidopsisDemoData/SequenceData/1_A01_customer/m54113_160913_184949.subreads.bam", "https://downloads.pacbcloud.com/public/SequelData/ArabidopsisDemoData/SequenceData/3_C01_customer/m54113_160914_092411.subreads.bam"]
      reference: "https://downloads.pacbcloud.com/public/SequelData/ArabidopsisDemoData/Assembly/Arabidopsis_assembly.fasta"
      algorithm: ["unitigs", "omnitigs", "trivialomnitigs"]

tests:
  "GCF_000008865.2_ASM886v2":
    k: [51]
    bcalm2_abundance_min: [1]
    circularised: [true]
    filter_retain: "NC_002695.2"
    preprocessing: "bcalm2"
    algorithm: ["unitigs"]