use_conda: true

# The test file must be given without file endings.
test_file: "GCF_000008865.2_ASM886v2_genomic"
experiment_file_urls: [
  #"https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/865/GCF_000008865.2_ASM886v2/GCF_000008865.2_ASM886v2_genomic.fna.gz", # has multiple records
  "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/025/GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_genomic.fna.gz"
]

